CREATE TABLE [dbo].[BPIndividual] (
    [BPMainID]             BIGINT         NOT NULL,
    [FirstName]            NVARCHAR (255) NOT NULL,
    [MiddleName]           NVARCHAR (255) NULL,
    [LastName]             NVARCHAR (255) NOT NULL,
    [Initials]             NVARCHAR (5)   NULL,
    [LiscenseNumber]       NVARCHAR (100) NULL,
    [LiscenseExpiryDate]   DATETIME       NULL,
    [GenderStatus]         CHAR (1)       NULL,
    [PassportNumber]       NVARCHAR (100) NULL,
    [NIDNumber]            NVARCHAR (100) NULL,
    [MaritalStatusCode]    NVARCHAR (10)  NULL,
    [TaxRegisterationCode] NVARCHAR (100) NULL,
    [TaxNumber]            NVARCHAR (100) NULL,
    [DateOfBirth]          DATETIME       NULL,
    [OccupationTypeID]     SMALLINT       NULL,
    [IsCompanyExternal]    BIT            CONSTRAINT [DF_BPIndividual_IsCompanyExternal] DEFAULT ((0)) NOT NULL,
    [CompanyName]          NVARCHAR (255) NULL,
    [CompanyAddress]       NVARCHAR (500) NULL,
    [CompanyPhone]         NVARCHAR (25)  NULL,
    [BPCompanyID]          BIGINT         NULL,
    [RowVersion]           BIGINT         CONSTRAINT [DF__BPIndivid__RowVe__611C5D5B] DEFAULT ((0)) NOT NULL,
    [RecCreatedBy]         NVARCHAR (100) NOT NULL,
    [RecCreatedDt]         DATETIME       NOT NULL,
    [RecLastUpdatedBy]     NVARCHAR (100) NOT NULL,
    [RecLastUpdatedDt]     DATETIME       NOT NULL,
    [NICExpDt]             DATETIME       NULL,
    [PassportExpDt]        DATETIME       NULL,
    [PassportCountryID]    SMALLINT       NULL,
    [IqamaNo]              NVARCHAR (100) NULL,
    [IqamaExpDt]           DATETIME       NULL,
    [UserDomainKey]        BIGINT         NOT NULL,
    CONSTRAINT [PK69] PRIMARY KEY CLUSTERED ([BPMainID] ASC),
    CONSTRAINT [RefBPMain123] FOREIGN KEY ([BPMainID]) REFERENCES [dbo].[BPMain] ([BPMainID]),
    CONSTRAINT [RefBPMain296] FOREIGN KEY ([BPCompanyID]) REFERENCES [dbo].[BPMain] ([BPMainID]),
    CONSTRAINT [RefCountry617] FOREIGN KEY ([PassportCountryID]) REFERENCES [dbo].[Country] ([CountryID]),
    CONSTRAINT [RefOccupationType292] FOREIGN KEY ([OccupationTypeID]) REFERENCES [dbo].[OccupationType] ([OccupationTypeID])
);

