CREATE TABLE [dbo].[Company] (
    [CompanyID]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [ParentCompany]      BIGINT          NULL,
    [OrgGroupID]         BIGINT          NULL,
    [CompanyCode]        NVARCHAR (100)  NULL,
    [CompanyName]        NVARCHAR (255)  NULL,
    [CompanyDescription] NVARCHAR (500)  NULL,
    [CompanyLegalName]   NVARCHAR (255)  NULL,
    [CRNumber]           NVARCHAR (100)  NULL,
    [UAN]                NVARCHAR (20)   NULL,
    [NTN]                NVARCHAR (100)  NULL,
    [PaidUpCapital]      DECIMAL (18, 5) NULL,
    [BusinessSegmentID]  SMALLINT        NOT NULL,
    [RowVersion]         BIGINT          CONSTRAINT [DF_Company_RowVersion] DEFAULT ((0)) NOT NULL,
    [IsActive]           BIT             CONSTRAINT [DF__Company__IsActiv__55BFB948] DEFAULT ((1)) NOT NULL,
    [IsDeleted]          BIT             CONSTRAINT [DF__Company__IsDelet__56B3DD81] DEFAULT ((0)) NOT NULL,
    [IsPrivate]          BIT             CONSTRAINT [DF__Company__IsPriva__57A801BA] DEFAULT ((0)) NOT NULL,
    [IsReadOnly]         BIT             CONSTRAINT [DF__Company__IsReadO__589C25F3] DEFAULT ((0)) NOT NULL,
    [RecCreatedDt]       DATETIME        NOT NULL,
    [RecCreatedBy]       NVARCHAR (100)  NOT NULL,
    [RecLastUpdatedDt]   DATETIME        NOT NULL,
    [RecLastUpdatedBy]   NVARCHAR (100)  NOT NULL,
    [UserDomainKey]      BIGINT          NOT NULL,
    CONSTRAINT [PK1] PRIMARY KEY NONCLUSTERED ([CompanyID] ASC),
    CONSTRAINT [RefBusinessSegment1401] FOREIGN KEY ([BusinessSegmentID]) REFERENCES [dbo].[BusinessSegment] ([BusinessSegmentID]),
    CONSTRAINT [RefCompany263] FOREIGN KEY ([ParentCompany]) REFERENCES [dbo].[Company] ([CompanyID]),
    CONSTRAINT [RefOrgGroup291] FOREIGN KEY ([OrgGroupID]) REFERENCES [dbo].[OrgGroup] ([OrgGroupID])
);

