CREATE TABLE [dbo].[EmpDocsInfo] (
    [EmployeeID]         BIGINT         NOT NULL,
    [NIC]                NVARCHAR (100) NULL,
    [NICExpDt]           DATETIME       NULL,
    [IqamaNo]            NVARCHAR (100) NULL,
    [IqamaExpDt]         DATETIME       NULL,
    [PassportNo]         NVARCHAR (100) NULL,
    [PassportExpDt]      DATETIME       NULL,
    [PassportCountryID]  SMALLINT       NULL,
    [VisaNo]             NVARCHAR (100) NULL,
    [VisaExpDt]          DATETIME       NULL,
    [VisaIssueCountryID] SMALLINT       NULL,
    [LicenseNo]          NVARCHAR (100) NULL,
    [LicenseExpDt]       DATETIME       NULL,
    [LicenseTypeID]      BIGINT         NULL,
    [InsuranceNo]        NVARCHAR (100) NULL,
    [InsuranceCompany]   NVARCHAR (100) NULL,
    [InsuranceDt]        DATETIME       NULL,
    [RowVersion]         BIGINT         CONSTRAINT [DF__EmpDocsIn__RowVe__1E9A6CE7] DEFAULT ((0)) NOT NULL,
    [IsActive]           BIT            CONSTRAINT [DF__EmpDocsIn__IsAct__1F8E9120] DEFAULT ((1)) NOT NULL,
    [IsPrivate]          BIT            CONSTRAINT [DF__EmpDocsIn__IsPri__2082B559] DEFAULT ((0)) NOT NULL,
    [IsDeleted]          BIT            CONSTRAINT [DF__EmpDocsIn__IsDel__2176D992] DEFAULT ((0)) NOT NULL,
    [IsReadOnly]         BIT            CONSTRAINT [DF__EmpDocsIn__IsRea__226AFDCB] DEFAULT ((0)) NOT NULL,
    [RecCreatedDt]       DATETIME       NOT NULL,
    [RecCreatedBy]       NVARCHAR (100) NOT NULL,
    [RecLastUpdatedDt]   DATETIME       NOT NULL,
    [RecLastUpdatedBy]   NVARCHAR (100) NOT NULL,
    [UserDomainKey]      BIGINT         NOT NULL,
    CONSTRAINT [PK43_1_2] PRIMARY KEY CLUSTERED ([EmployeeID] ASC),
    CONSTRAINT [RefEmployee348] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employee] ([EmployeeID]) ON DELETE CASCADE,
    CONSTRAINT [RefLicenseType418] FOREIGN KEY ([LicenseTypeID]) REFERENCES [dbo].[LicenseType] ([LicenseTypeID])
);



