CREATE TABLE [dbo].[Employee] (
    [EmployeeID]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [EmpCode]          NVARCHAR (100) NOT NULL,
    [EmpFName]         NVARCHAR (255) NOT NULL,
    [CompanyID]        BIGINT         NOT NULL,
    [EmpStatusID]      BIGINT         NOT NULL,
    [EmpMName]         NVARCHAR (255) NULL,
    [EmpLName]         NVARCHAR (255) NULL,
    [DOB]              DATETIME       NOT NULL,
    [Gender]           CHAR (1)       NULL,
    [Nationality]      SMALLINT       NULL,
    [Notes]            NVARCHAR (500) NULL,
    [AddNotes1]        NVARCHAR (500) NULL,
    [AddNotes2]        NVARCHAR (500) NULL,
    [AddNotes3]        NVARCHAR (500) NULL,
    [AddNotes4]        NVARCHAR (500) NULL,
    [AddNotes5]        NVARCHAR (500) NULL,
    [RowVersion]       BIGINT         CONSTRAINT [DF__Employee__RowVer__32A16594] DEFAULT ((0)) NOT NULL,
    [IsActive]         BIT            CONSTRAINT [DF__Employee__IsActi__339589CD] DEFAULT ((1)) NOT NULL,
    [IsDeleted]        BIT            CONSTRAINT [DF__Employee__IsDele__3489AE06] DEFAULT ((0)) NOT NULL,
    [IsPrivate]        BIT            CONSTRAINT [DF__Employee__IsPriv__357DD23F] DEFAULT ((0)) NOT NULL,
    [IsReadOnly]       BIT            CONSTRAINT [DF__Employee__IsRead__3671F678] DEFAULT ((0)) NOT NULL,
    [RecCreatedDt]     DATETIME       NOT NULL,
    [RecCreatedBy]     NVARCHAR (100) NOT NULL,
    [RecLastUpdatedDt] DATETIME       NOT NULL,
    [RecLastUpdatedBy] NVARCHAR (100) NOT NULL,
    [UserDomainKey]    BIGINT         NOT NULL,
    CONSTRAINT [PK38] PRIMARY KEY CLUSTERED ([EmployeeID] ASC),
    CONSTRAINT [RefCompany354] FOREIGN KEY ([CompanyID]) REFERENCES [dbo].[Company] ([CompanyID]),
    CONSTRAINT [RefEmpStatus353] FOREIGN KEY ([EmpStatusID]) REFERENCES [dbo].[EmpStatus] ([EmpStatusID]),
    CONSTRAINT [RefNationality355] FOREIGN KEY ([Nationality]) REFERENCES [dbo].[Country] ([CountryID])
);

