CREATE TABLE [dbo].[RADriver] (
    [RADriverID]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [ChaufferID]       BIGINT         NULL,
    [RAMainID]         BIGINT         NOT NULL,
    [DriverName]       NVARCHAR (100) NULL,
    [IsChauffer]       BIT            NOT NULL,
    [DesigGradeID]     BIGINT         NULL,
    [TariffType]       NVARCHAR (355) NOT NULL,
    [Rate]             FLOAT (53)     NOT NULL,
    [TotalCharge]      FLOAT (53)     NOT NULL,
    [ChargedDay]       INT            NOT NULL,
    [ChargedHour]      INT            NOT NULL,
    [ChargedMinute]    INT            NOT NULL,
    [LicenseExpDt]     DATETIME       NULL,
    [LicenseNo]        NVARCHAR (100) NULL,
    [StartDtTime]      DATETIME       NOT NULL,
    [EndDtTime]        DATETIME       NOT NULL,
    [RowVersion]       BIGINT         CONSTRAINT [DF__RADriver__RowVer__6C83EE66] DEFAULT ((0)) NOT NULL,
    [IsActive]         BIT            CONSTRAINT [DF__RADriver__IsActi__6D78129F] DEFAULT ((1)) NOT NULL,
    [IsDeleted]        BIT            CONSTRAINT [DF__RADriver__IsDele__6E6C36D8] DEFAULT ((0)) NOT NULL,
    [IsPrivate]        BIT            CONSTRAINT [DF__RADriver__IsPriv__6F605B11] DEFAULT ((0)) NOT NULL,
    [IsReadOnly]       BIT            CONSTRAINT [DF__RADriver__IsRead__70547F4A] DEFAULT ((0)) NOT NULL,
    [RecCreatedDt]     DATETIME       NOT NULL,
    [RecCreatedBy]     NVARCHAR (100) NOT NULL,
    [RecLastUpdatedDt] DATETIME       NOT NULL,
    [RecLastUpdatedBy] NVARCHAR (100) NOT NULL,
    [UserDomainKey]    BIGINT         NOT NULL,
    CONSTRAINT [PK126_2_1_1] PRIMARY KEY NONCLUSTERED ([RADriverID] ASC),
    CONSTRAINT [RefDesigGrade540] FOREIGN KEY ([DesigGradeID]) REFERENCES [dbo].[DesigGrade] ([DesigGradeID]),
    CONSTRAINT [RefEmployee532] FOREIGN KEY ([ChaufferID]) REFERENCES [dbo].[Employee] ([EmployeeID]),
    CONSTRAINT [RefRAMain533] FOREIGN KEY ([RAMainID]) REFERENCES [dbo].[RAMain] ([RAMainID])
);

