CREATE TABLE [dbo].[RAHireGroup] (
    [RAHireGroupID]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [AllocationStatusID]    SMALLINT       NOT NULL,
    [HireGroupDetailID]     BIGINT         NOT NULL,
    [VehicleID]             BIGINT         NULL,
    [StandardRate]          FLOAT (53)     NOT NULL,
    [AllowedMileage]        INT            NULL,
    [DropOffCharge]         FLOAT (53)     NOT NULL,
    [RowVersion]            BIGINT         CONSTRAINT [DF__RAHireGro__RowVe__1BDDFBCD] DEFAULT ((0)) NOT NULL,
    [IsActive]              BIT            CONSTRAINT [DF__RAHireGro__IsAct__1CD22006] DEFAULT ((1)) NOT NULL,
    [IsDeleted]             BIT            CONSTRAINT [DF__RAHireGro__IsDel__1DC6443F] DEFAULT ((0)) NOT NULL,
    [IsPrivate]             BIT            CONSTRAINT [DF__RAHireGro__IsPri__1EBA6878] DEFAULT ((0)) NOT NULL,
    [IsReadOnly]            BIT            CONSTRAINT [DF__RAHireGro__IsRea__1FAE8CB1] DEFAULT ((0)) NOT NULL,
    [RecCreatedDt]          DATETIME       NOT NULL,
    [RecCreatedBy]          NVARCHAR (100) NOT NULL,
    [RecLastUpdatedDt]      DATETIME       NOT NULL,
    [RecLastUpdatedBy]      NVARCHAR (100) NOT NULL,
    [RAMainID]              BIGINT         NOT NULL,
    [TariffTypeCode]        NVARCHAR (100) NOT NULL,
    [RentalChargeStartDate] DATETIME       NOT NULL,
    [RentalChargeEndDate]   DATETIME       NOT NULL,
    [TotalStandardCharge]   FLOAT (53)     NOT NULL,
    [TotalExcMileageCharge] FLOAT (53)     NOT NULL,
    [TotalExcMileage]       INT            NOT NULL,
    [ExcessMileageRt]       FLOAT (53)     NOT NULL,
    [GraceDay]              INT            NOT NULL,
    [GraceHour]             INT            NOT NULL,
    [GraceMinute]           INT            NOT NULL,
    [ChargedDay]            INT            NOT NULL,
    [ChargedHour]           INT            NOT NULL,
    [ChargedMinute]         INT            NOT NULL,
    [UserDomainKey]         BIGINT         NOT NULL,
    CONSTRAINT [PK89_1_3_1] PRIMARY KEY NONCLUSTERED ([RAHireGroupID] ASC),
    CONSTRAINT [RefAllocationStatus502] FOREIGN KEY ([AllocationStatusID]) REFERENCES [dbo].[AllocationStatus] ([AllocationStatusID]),
    CONSTRAINT [RefHireGroupDetail503] FOREIGN KEY ([HireGroupDetailID]) REFERENCES [dbo].[HireGroupDetail] ([HireGroupDetailID]),
    CONSTRAINT [RefRAMain504] FOREIGN KEY ([RAMainID]) REFERENCES [dbo].[RAMain] ([RAMainID]),
    CONSTRAINT [RefVehicle523] FOREIGN KEY ([VehicleID]) REFERENCES [dbo].[Vehicle] ([VehicleID])
);

