CREATE TABLE [dbo].[RAMain] (
    [RAMainID]                 BIGINT         IDENTITY (1, 1) NOT NULL,
    [RAMainDescription]        NVARCHAR (500) NULL,
    [StartDtTime]              DATETIME       NOT NULL,
    [EndDtTime]                DATETIME       NOT NULL,
    [RowVersion]               BIGINT         CONSTRAINT [DF__RAMain__RowVersi__1EC48A19] DEFAULT ((0)) NOT NULL,
    [IsActive]                 BIT            CONSTRAINT [DF__RAMain__IsActive__1FB8AE52] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                BIT            CONSTRAINT [DF__RAMain__IsDelete__20ACD28B] DEFAULT ((0)) NOT NULL,
    [IsPrivate]                BIT            CONSTRAINT [DF__RAMain__IsPrivat__21A0F6C4] DEFAULT ((0)) NOT NULL,
    [IsReadOnly]               BIT            CONSTRAINT [DF__RAMain__IsReadOn__22951AFD] DEFAULT ((0)) NOT NULL,
    [RecCreatedDt]             DATETIME       NOT NULL,
    [RecCreatedBy]             NVARCHAR (100) NOT NULL,
    [RecLastUpdatedDt]         DATETIME       NOT NULL,
    [RecLastUpdatedBy]         NVARCHAR (100) NOT NULL,
    [RAStatusID]               SMALLINT       NOT NULL,
    [PaymentTermID]            SMALLINT       NOT NULL,
    [CloseLocation]            BIGINT         NOT NULL,
    [OpenLocation]             BIGINT         NOT NULL,
    [OperationID]              BIGINT         NOT NULL,
    [BPMainID]                 BIGINT         NOT NULL,
    [TotalVehicleCharge]       FLOAT (53)     CONSTRAINT [DF__RAMain__TotalVeh__23893F36] DEFAULT ((0)) NOT NULL,
    [TotalInsuranceCharge]     FLOAT (53)     CONSTRAINT [DF__RAMain__TotalIns__247D636F] DEFAULT ((0)) NOT NULL,
    [VoucherDiscount]          FLOAT (53)     CONSTRAINT [DF__RAMain__VoucherD__257187A8] DEFAULT ((0)) NOT NULL,
    [SeasonalDiscount]         FLOAT (53)     CONSTRAINT [DF__RAMain__Seasonal__2665ABE1] DEFAULT ((0)) NOT NULL,
    [SpecialDiscount]          FLOAT (53)     CONSTRAINT [DF__RAMain__SpecialD__2759D01A] DEFAULT ((0)) NOT NULL,
    [TotalDropOffCharge]       FLOAT (53)     CONSTRAINT [DF__RAMain__TotalDro__284DF453] DEFAULT ((0)) NOT NULL,
    [NetBillAfterDiscount]     FLOAT (53)     CONSTRAINT [DF__RAMain__NetBillA__2942188C] DEFAULT ((0)) NOT NULL,
    [TotalExcessMileageCharge] FLOAT (53)     CONSTRAINT [DF__RAMain__TotalExc__2A363CC5] DEFAULT ((0)) NOT NULL,
    [TotalServiceCharge]       FLOAT (53)     CONSTRAINT [DF__RAMain__TotalSer__2B2A60FE] DEFAULT ((0)) NOT NULL,
    [TotalDriverCharge]        FLOAT (53)     CONSTRAINT [DF__RAMain__TotalDri__2C1E8537] DEFAULT ((0)) NOT NULL,
    [TotalAdditionalCharge]    FLOAT (53)     CONSTRAINT [DF__RAMain__TotalAdd__2D12A970] DEFAULT ((0)) NOT NULL,
    [TotalOtherCharge]         FLOAT (53)     CONSTRAINT [DF__RAMain__TotalOth__2E06CDA9] DEFAULT ((0)) NULL,
    [AmountPaid]               FLOAT (53)     CONSTRAINT [DF__RAMain__AmountPa__2EFAF1E2] DEFAULT ((0)) NOT NULL,
    [Balance]                  FLOAT (53)     CONSTRAINT [DF__RAMain__Balance__2FEF161B] DEFAULT ((0)) NOT NULL,
    [SpecialDiscountPerc]      FLOAT (53)     NULL,
    [StandardDiscount]         FLOAT (53)     CONSTRAINT [DF__RAMain__Standard__30E33A54] DEFAULT ((0)) NOT NULL,
    [RentersName]              NVARCHAR (255) NULL,
    [RentersLicenseNumber]     NVARCHAR (100) NULL,
    [RentersLicenseExpDt]      DATETIME       NULL,
    [IsSpecialDiscountPerc]    BIT            CONSTRAINT [DF__RAMain__IsSpecia__31D75E8D] DEFAULT ((1)) NOT NULL,
    [RABookingID]              BIGINT         NULL,
    [UserDomainKey]            BIGINT         NOT NULL,
    CONSTRAINT [PK20_1_1] PRIMARY KEY NONCLUSTERED ([RAMainID] ASC),
    CONSTRAINT [RefBPMain506] FOREIGN KEY ([BPMainID]) REFERENCES [dbo].[BPMain] ([BPMainID]),
    CONSTRAINT [RefOperation501] FOREIGN KEY ([OperationID]) REFERENCES [dbo].[Operation] ([OperationID]),
    CONSTRAINT [RefOperationsWorkplace498] FOREIGN KEY ([CloseLocation]) REFERENCES [dbo].[OperationsWorkplace] ([OperationsWorkplaceID]),
    CONSTRAINT [RefOperationsWorkplace499] FOREIGN KEY ([OpenLocation]) REFERENCES [dbo].[OperationsWorkplace] ([OperationsWorkplaceID]),
    CONSTRAINT [RefPaymentTerm497] FOREIGN KEY ([PaymentTermID]) REFERENCES [dbo].[PaymentTerm] ([PaymentTermID]),
    CONSTRAINT [RefRAMain620] FOREIGN KEY ([RABookingID]) REFERENCES [dbo].[RAMain] ([RAMainID]),
    CONSTRAINT [RefRAStatus496] FOREIGN KEY ([RAStatusID]) REFERENCES [dbo].[RAStatus] ([RAStatusID])
);

