CREATE TABLE [dbo].[RAPayment] (
    [RAPaymentID]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [PaymentModeID]      SMALLINT       NOT NULL,
    [RAMainID]           BIGINT         NOT NULL,
    [RAPaymentDt]        DATETIME       NOT NULL,
    [RAPaymentAmount]    FLOAT (53)     NOT NULL,
    [ChequeNumber]       NVARCHAR (100) NULL,
    [CreditCardNumber]   NVARCHAR (100) NULL,
    [IssueDate]          DATETIME       NULL,
    [ClearanceDate]      DATETIME       NULL,
    [CreditCardType]     NVARCHAR (100) NULL,
    [Bank]               NVARCHAR (100) NULL,
    [CreditCardExpiryDt] DATETIME       NULL,
    [PaidBy]             NVARCHAR (100) NULL,
    [IsActive]           BIT            NOT NULL,
    [IsDeleted]          BIT            NOT NULL,
    [IsPrivate]          BIT            NOT NULL,
    [IsReadOnly]         BIT            NOT NULL,
    [RowVersion]         BIGINT         NOT NULL,
    [RecCreatedDt]       DATETIME       NOT NULL,
    [RecLastUpdatedDt]   DATETIME       NOT NULL,
    [RecCreatedBy]       NVARCHAR (100) NOT NULL,
    [RecLastUpdatedBy]   NVARCHAR (100) NOT NULL,
    [UserDomainKey]      BIGINT         NOT NULL,
    CONSTRAINT [PK80_3_1_1] PRIMARY KEY NONCLUSTERED ([RAPaymentID] ASC),
    CONSTRAINT [RefPaymentMode541] FOREIGN KEY ([PaymentModeID]) REFERENCES [dbo].[PaymentMode] ([PaymentModeID]),
    CONSTRAINT [RefRAMain542] FOREIGN KEY ([RAMainID]) REFERENCES [dbo].[RAMain] ([RAMainID])
);

