CREATE TABLE [dbo].[RAServiceItem] (
    [RAServiceItemID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [RAServiceItemDescription] NVARCHAR (500) NULL,
    [ServiceItemID]            BIGINT         NOT NULL,
    [RAMainID]                 BIGINT         NOT NULL,
    [Quantity]                 INT            NOT NULL,
    [StartDtTime]              DATETIME       NOT NULL,
    [EndDtTime]                DATETIME       NOT NULL,
    [ServiceRate]              FLOAT (53)     NOT NULL,
    [ServiceCharge]            FLOAT (53)     NOT NULL,
    [ChargedDay]               INT            NOT NULL,
    [ChargedHour]              INT            NOT NULL,
    [ChargedMinute]            INT            NOT NULL,
    [TariffType]               NVARCHAR (100) NOT NULL,
    [RowVersion]               BIGINT         CONSTRAINT [DF__RAService__RowVe__3DFE09A7] DEFAULT ((0)) NOT NULL,
    [IsActive]                 BIT            CONSTRAINT [DF__RAService__IsAct__3EF22DE0] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                BIT            CONSTRAINT [DF__RAService__IsDel__3FE65219] DEFAULT ((0)) NOT NULL,
    [IsPrivate]                BIT            CONSTRAINT [DF__RAService__IsPri__40DA7652] DEFAULT ((0)) NOT NULL,
    [IsReadOnly]               BIT            CONSTRAINT [DF__RAService__IsRea__41CE9A8B] DEFAULT ((0)) NOT NULL,
    [RecCreatedDt]             DATETIME       NOT NULL,
    [RecCreatedBy]             NVARCHAR (100) NOT NULL,
    [RecLastUpdatedDt]         DATETIME       NOT NULL,
    [RecLastUpdatedBy]         NVARCHAR (100) NOT NULL,
    [UserDomainKey]            BIGINT         NOT NULL,
    CONSTRAINT [PK126_2_4] PRIMARY KEY NONCLUSTERED ([RAServiceItemID] ASC),
    CONSTRAINT [RefRAMain515] FOREIGN KEY ([RAMainID]) REFERENCES [dbo].[RAMain] ([RAMainID]),
    CONSTRAINT [RefServiceItem514] FOREIGN KEY ([ServiceItemID]) REFERENCES [dbo].[ServiceItem] ([ServiceItemID])
);

