CREATE TABLE [dbo].[SeasonalDiscount] (
    [SeasonalDiscountID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [ChildSeasonalDiscountID] BIGINT         NULL,
    [SeasonalDiscountMainID]  BIGINT         NOT NULL,
    [OperationsWorkplaceID]   BIGINT         NULL,
    [VehicleMakeID]           SMALLINT       NULL,
    [BPRatingTypeID]          SMALLINT       NULL,
    [VehicleCategoryID]       SMALLINT       NULL,
    [VehicleModelID]          SMALLINT       NULL,
    [HireGroupID]             BIGINT         NULL,
    [CustomerType]            SMALLINT       NOT NULL,
    [ModelYear]               SMALLINT       NULL,
    [DiscountPerc]            FLOAT (53)     NOT NULL,
    [SeasonalDiscountStartDt] DATETIME       NOT NULL,
    [SeasonalDiscountEndDt]   DATETIME       NOT NULL,
    [RevisionNumber]          BIGINT         NOT NULL,
    [IsActive]                BIT            NOT NULL,
    [IsDeleted]               BIT            NOT NULL,
    [IsPrivate]               BIT            NOT NULL,
    [IsReadOnly]              BIT            NOT NULL,
    [RowVersion]              BIGINT         NOT NULL,
    [RecCreatedDt]            DATETIME       NOT NULL,
    [RecLastUpdatedDt]        DATETIME       NOT NULL,
    [RecCreatedBy]            NVARCHAR (100) NOT NULL,
    [RecLastUpdatedBy]        NVARCHAR (100) NOT NULL,
    [UserDomainKey]           BIGINT         NOT NULL,
    CONSTRAINT [PK80_2] PRIMARY KEY NONCLUSTERED ([SeasonalDiscountID] ASC),
    CONSTRAINT [RefBPRatingType413] FOREIGN KEY ([BPRatingTypeID]) REFERENCES [dbo].[BPRatingType] ([BPRatingTypeID]),
    CONSTRAINT [RefHireGroup575] FOREIGN KEY ([HireGroupID]) REFERENCES [dbo].[HireGroup] ([HireGroupID]),
    CONSTRAINT [RefOperationsWorkplace412] FOREIGN KEY ([OperationsWorkplaceID]) REFERENCES [dbo].[OperationsWorkplace] ([OperationsWorkplaceID]),
    CONSTRAINT [RefSeasonalDiscount409] FOREIGN KEY ([ChildSeasonalDiscountID]) REFERENCES [dbo].[SeasonalDiscount] ([SeasonalDiscountID]),
    CONSTRAINT [RefSeasonalDiscountMain568] FOREIGN KEY ([SeasonalDiscountMainID]) REFERENCES [dbo].[SeasonalDiscountMain] ([SeasonalDiscountMainID]) ON DELETE CASCADE,
    CONSTRAINT [RefVehicleCategory563] FOREIGN KEY ([VehicleCategoryID]) REFERENCES [dbo].[VehicleCategory] ([VehicleCategoryID]),
    CONSTRAINT [RefVehicleMake562] FOREIGN KEY ([VehicleMakeID]) REFERENCES [dbo].[VehicleMake] ([VehicleMakeID]),
    CONSTRAINT [RefVehicleModel564] FOREIGN KEY ([VehicleModelID]) REFERENCES [dbo].[VehicleModel] ([VehicleModelID])
);



