CREATE TABLE [dbo].[TariffType] (
    [TariffTypeID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [OperationID]           BIGINT         NOT NULL,
    [MeasurementUnitID]     SMALLINT       NULL,
    [TariffTypeCode]        NVARCHAR (100) NOT NULL,
    [TariffTypeName]        NVARCHAR (255) NULL,
    [TariffTypeDescription] NVARCHAR (500) NULL,
    [PricingStrategyID]     INT            NOT NULL,
    [DurationFrom]          SMALLINT       NOT NULL,
    [DurationTo]            SMALLINT       NOT NULL,
    [GracePeriod]           FLOAT (53)     NOT NULL,
    [EffectiveDate]         DATETIME       NOT NULL,
    [RowVersion]            BIGINT         CONSTRAINT [DF__TariffTyp__RowVe__3513BDEB] DEFAULT ((0)) NOT NULL,
    [RevisionNumber]        BIGINT         CONSTRAINT [DF__TariffTyp__Revis__3607E224] DEFAULT ((0)) NOT NULL,
    [ChildTariffTypeID]     BIGINT         NULL,
    [RecCreatedDt]          DATETIME       NOT NULL,
    [RecLastUpdatedDt]      DATETIME       NOT NULL,
    [RecLastUpdatedBy]      NVARCHAR (100) NOT NULL,
    [RecCreatedBy]          NVARCHAR (100) NOT NULL,
    [IsActive]              BIT            CONSTRAINT [DF__TariffTyp__IsAct__36FC065D] DEFAULT ((1)) NOT NULL,
    [IsDeleted]             BIT            CONSTRAINT [DF__TariffTyp__IsDel__37F02A96] DEFAULT ((0)) NOT NULL,
    [IsPrivate]             BIT            CONSTRAINT [DF__TariffTyp__IsPri__38E44ECF] DEFAULT ((0)) NOT NULL,
    [IsReadOnly]            BIT            CONSTRAINT [DF__TariffTyp__IsRea__39D87308] DEFAULT ((0)) NOT NULL,
    [UserDomainKey]         BIGINT         NOT NULL,
    CONSTRAINT [PK78] PRIMARY KEY NONCLUSTERED ([TariffTypeID] ASC),
    CONSTRAINT [RefMeasurementUnit358] FOREIGN KEY ([MeasurementUnitID]) REFERENCES [dbo].[MeasurementUnit] ([MeasurementUnitID]),
    CONSTRAINT [RefOperation257] FOREIGN KEY ([OperationID]) REFERENCES [dbo].[Operation] ([OperationID]),
    CONSTRAINT [RefPricingStrategy376] FOREIGN KEY ([PricingStrategyID]) REFERENCES [dbo].[PricingStrategy] ([PricingStrategyID]),
    CONSTRAINT [RefTariffType364] FOREIGN KEY ([ChildTariffTypeID]) REFERENCES [dbo].[TariffType] ([TariffTypeID])
);

