CREATE TABLE [dbo].[Vehicle] (
    [VehicleID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [IsBranchOwner]               BIT             CONSTRAINT [DF__Vehicle__IsBranc__1FF8A574] DEFAULT ((0)) NULL,
    [PlateNumber]                 NVARCHAR (50)   NULL,
    [VehicleCode]                 NVARCHAR (100)  NOT NULL,
    [VehicleName]                 NVARCHAR (255)  NULL,
    [ModelYear]                   SMALLINT        NOT NULL,
    [HireGroupID]                 BIGINT          NULL,
    [FleetPoolID]                 BIGINT          NULL,
    [Color]                       NVARCHAR (50)   NOT NULL,
    [OperationsWorkPlaceID]       BIGINT          NULL,
    [FuelLevel]                   SMALLINT        NULL,
    [TankSize]                    SMALLINT        CONSTRAINT [DF_Vehicle_TankSize] DEFAULT ((0)) NOT NULL,
    [InitialOdometer]             INT             NOT NULL,
    [CurrentOdometer]             INT             NOT NULL,
    [RegisterationDate]           DATETIME        NULL,
    [VehicleMakeID]               SMALLINT        NOT NULL,
    [VehicleCategoryID]           SMALLINT        NOT NULL,
    [VehicleModelID]              SMALLINT        NOT NULL,
    [VehicleStatusID]             SMALLINT        NOT NULL,
    [RecCreatedDt]                DATETIME        NOT NULL,
    [RecCreatedBy]                NVARCHAR (100)  NOT NULL,
    [RecLastUpdatedDt]            DATETIME        NOT NULL,
    [RecLastUpdatedBy]            NVARCHAR (100)  NOT NULL,
    [RowVersion]                  BIGINT          CONSTRAINT [DF__Vehicle__RowVers__20ECC9AD] DEFAULT ((0)) NOT NULL,
    [FuelTypeID]                  SMALLINT        NOT NULL,
    [TransmissionTypeID]          SMALLINT        NOT NULL,
    [IsActive]                    BIT             CONSTRAINT [DF__Vehicle__IsActiv__21E0EDE6] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                   BIT             NOT NULL,
    [IsReadOnly]                  BIT             NOT NULL,
    [IsPrivate]                   BIT             NOT NULL,
    [VehicleCondition]            NVARCHAR (255)  CONSTRAINT [DF__Vehicle__Vehicle__00FF1D08] DEFAULT ('000000000000000000000000000') NOT NULL,
    [VehicleConditionDescription] NVARCHAR (1500) NULL,
    [RegisterationExpiryDate]     DATETIME        NULL,
    [UserDomainKey]               BIGINT          NOT NULL,
    CONSTRAINT [PK5] PRIMARY KEY NONCLUSTERED ([VehicleID] ASC),
    CONSTRAINT [FK_Vehicle_VehicleStatus] FOREIGN KEY ([VehicleStatusID]) REFERENCES [dbo].[VehicleStatus] ([VehicleStatusID]),
    CONSTRAINT [RefFleetPool136] FOREIGN KEY ([FleetPoolID]) REFERENCES [dbo].[FleetPool] ([FleetPoolID]),
    CONSTRAINT [RefFuelType330] FOREIGN KEY ([FuelTypeID]) REFERENCES [dbo].[FuelType] ([FuelTypeID]),
    CONSTRAINT [RefHireGroup95] FOREIGN KEY ([HireGroupID]) REFERENCES [dbo].[HireGroup] ([HireGroupID]),
    CONSTRAINT [RefOperationsWorkplace209] FOREIGN KEY ([OperationsWorkPlaceID]) REFERENCES [dbo].[OperationsWorkplace] ([OperationsWorkplaceID]),
    CONSTRAINT [RefTransmissionType331] FOREIGN KEY ([TransmissionTypeID]) REFERENCES [dbo].[TransmissionType] ([TransmissionTypeID]),
    CONSTRAINT [RefVehicleCategory316] FOREIGN KEY ([VehicleCategoryID]) REFERENCES [dbo].[VehicleCategory] ([VehicleCategoryID]),
    CONSTRAINT [RefVehicleMake311] FOREIGN KEY ([VehicleMakeID]) REFERENCES [dbo].[VehicleMake] ([VehicleMakeID]),
    CONSTRAINT [RefVehicleModel324] FOREIGN KEY ([VehicleModelID]) REFERENCES [dbo].[VehicleModel] ([VehicleModelID])
);

