//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cares.Implementation.Resources.RentalAgreement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RentalAgreement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RentalAgreement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cares.Implementation.Resources.RentalAgreement.RentalAgreement", typeof(RentalAgreement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking with Id not found..
        /// </summary>
        public static string BookingNotFound {
            get {
                return ResourceManager.GetString("BookingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Partner with this name already exists.
        /// </summary>
        public static string BusinessPartnerAlreadyExists {
            get {
                return ResourceManager.GetString("BusinessPartnerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Partner with Id not found..
        /// </summary>
        public static string BusinessPartnerNotFound {
            get {
                return ResourceManager.GetString("BusinessPartnerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate not defined for Chauffer..
        /// </summary>
        public static string ChaufferRateNotDefinedForChauffer {
            get {
                return ResourceManager.GetString("ChaufferRateNotDefinedForChauffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge not defined for Additional Driver..
        /// </summary>
        public static string DriverChargeNotDefined {
            get {
                return ResourceManager.GetString("DriverChargeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add any further Rental Agreement under current domain!.
        /// </summary>
        public static string ExceedingDomainLimitForRAError {
            get {
                return ResourceManager.GetString("ExceedingDomainLimitForRAError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Rate not defined for selected Hire Group Insurance..
        /// </summary>
        public static string InsuranceRateNotDefinedForHireGroupInsurance {
            get {
                return ResourceManager.GetString("InsuranceRateNotDefinedForHireGroupInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain License Detail user claim not found.
        /// </summary>
        public static string NoDomainLicenseDetailClaim {
            get {
                return ResourceManager.GetString("NoDomainLicenseDetailClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone not found in system..
        /// </summary>
        public static string PhoneNotFound {
            get {
                return ResourceManager.GetString("PhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaHireGroup Insurance not found in system..
        /// </summary>
        public static string RaHireGroupInsuranceNotFound {
            get {
                return ResourceManager.GetString("RaHireGroupInsuranceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaHireGroup not found in system..
        /// </summary>
        public static string RaHireGroupNotFound {
            get {
                return ResourceManager.GetString("RaHireGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Agreement not found in system..
        /// </summary>
        public static string RentalAgreementNotFound {
            get {
                return ResourceManager.GetString("RentalAgreementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaAdditionalCharge not found in system..
        /// </summary>
        public static string RentalAgreementService_RaAdditionalChargeNotFound {
            get {
                return ResourceManager.GetString("RentalAgreementService_RaAdditionalChargeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaCustomerDocument not found in system..
        /// </summary>
        public static string RentalAgreementService_RaCustomerDocumentNotFound {
            get {
                return ResourceManager.GetString("RentalAgreementService_RaCustomerDocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaDriver not found in system..
        /// </summary>
        public static string RentalAgreementService_RaDriverNotFound {
            get {
                return ResourceManager.GetString("RentalAgreementService_RaDriverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaPayment not found in system..
        /// </summary>
        public static string RentalAgreementService_RaPaymentNotFound {
            get {
                return ResourceManager.GetString("RentalAgreementService_RaPaymentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaServiceItem not found in system..
        /// </summary>
        public static string RentalAgreementService_RaServiceItemNotFound {
            get {
                return ResourceManager.GetString("RentalAgreementService_RaServiceItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaStatus not found in system..
        /// </summary>
        public static string RentalAgreementService_RaStatusNotFound {
            get {
                return ResourceManager.GetString("RentalAgreementService_RaStatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Rate not defined for selected Service Item..
        /// </summary>
        public static string ServiceRateNotDefinedForServiceItem {
            get {
                return ResourceManager.GetString("ServiceRateNotDefinedForServiceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Tariff Rate not defined for selected Hire Group..
        /// </summary>
        public static string StandardTariffRateNotDefinedForRentalCharge {
            get {
                return ResourceManager.GetString("StandardTariffRateNotDefinedForRentalCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Type not defined for selected time period and operation..
        /// </summary>
        public static string TariffTypeNotDefinedForHireGroupInsurance {
            get {
                return ResourceManager.GetString("TariffTypeNotDefinedForHireGroupInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Type not defined for selected time period and operation..
        /// </summary>
        public static string TariffTypeNotDefinedForRaDriver {
            get {
                return ResourceManager.GetString("TariffTypeNotDefinedForRaDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Type not defined for selected time period and operation..
        /// </summary>
        public static string TariffTypeNotDefinedForRentalCharge {
            get {
                return ResourceManager.GetString("TariffTypeNotDefinedForRentalCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Type not defined for selected time period and operation..
        /// </summary>
        public static string TariffTypeNotDefinedForServiceItem {
            get {
                return ResourceManager.GetString("TariffTypeNotDefinedForServiceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle not found in system..
        /// </summary>
        public static string VehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleNotFound", resourceCulture);
            }
        }
    }
}
