//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cares.Web.Resources.EmployeeManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Employee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Employee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cares.Web.Resources.EmployeeManagement.Employee", typeof(Employee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        public static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Locations.
        /// </summary>
        public static string AuthorizedLocations {
            get {
                return ResourceManager.GetString("AuthorizedLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Operation.
        /// </summary>
        public static string DefaultOperation {
            get {
                return ResourceManager.GetString("DefaultOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Operations Workplace.
        /// </summary>
        public static string DefaultOperationsWorkplace {
            get {
                return ResourceManager.GetString("DefaultOperationsWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Grade.
        /// </summary>
        public static string DesignationGrade {
            get {
                return ResourceManager.GetString("DesignationGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Info..
        /// </summary>
        public static string DocumentInfo {
            get {
                return ResourceManager.GetString("DocumentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Detail.
        /// </summary>
        public static string EmployeeDetail {
            get {
                return ResourceManager.GetString("EmployeeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string EmployeeLabel {
            get {
                return ResourceManager.GetString("EmployeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Status.
        /// </summary>
        public static string EmployeeStatus {
            get {
                return ResourceManager.GetString("EmployeeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Company.
        /// </summary>
        public static string InsuranceCompany {
            get {
                return ResourceManager.GetString("InsuranceCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Date.
        /// </summary>
        public static string InsuranceDate {
            get {
                return ResourceManager.GetString("InsuranceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Number.
        /// </summary>
        public static string InsuranceNumber {
            get {
                return ResourceManager.GetString("InsuranceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iqama Expiry Date.
        /// </summary>
        public static string IqamaExpiryDate {
            get {
                return ResourceManager.GetString("IqamaExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iqama Number.
        /// </summary>
        public static string IqamaNumber {
            get {
                return ResourceManager.GetString("IqamaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Info..
        /// </summary>
        public static string JobInfo {
            get {
                return ResourceManager.GetString("JobInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Progress..
        /// </summary>
        public static string JobProgress {
            get {
                return ResourceManager.GetString("JobProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Date.
        /// </summary>
        public static string JoiningDate {
            get {
                return ResourceManager.GetString("JoiningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining End Date.
        /// </summary>
        public static string JoiningEndDate {
            get {
                return ResourceManager.GetString("JoiningEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Start Date.
        /// </summary>
        public static string JoiningStartDate {
            get {
                return ResourceManager.GetString("JoiningStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Expiry Date.
        /// </summary>
        public static string LicenseExpiryDate {
            get {
                return ResourceManager.GetString("LicenseExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Number.
        /// </summary>
        public static string LicenseNumber {
            get {
                return ResourceManager.GetString("LicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Type.
        /// </summary>
        public static string LicenseType {
            get {
                return ResourceManager.GetString("LicenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIC.
        /// </summary>
        public static string NIC {
            get {
                return ResourceManager.GetString("NIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIC Expiry Date.
        /// </summary>
        public static string NICExpDate {
            get {
                return ResourceManager.GetString("NICExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes .
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes 1.
        /// </summary>
        public static string Notes1 {
            get {
                return ResourceManager.GetString("Notes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes 2.
        /// </summary>
        public static string Notes2 {
            get {
                return ResourceManager.GetString("Notes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes 3.
        /// </summary>
        public static string Notes3 {
            get {
                return ResourceManager.GetString("Notes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes 4.
        /// </summary>
        public static string Notes4 {
            get {
                return ResourceManager.GetString("Notes4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes 5.
        /// </summary>
        public static string Notes5 {
            get {
                return ResourceManager.GetString("Notes5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Workplace.
        /// </summary>
        public static string OperationsWorkplace {
            get {
                return ResourceManager.GetString("OperationsWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Country.
        /// </summary>
        public static string PassportCountry {
            get {
                return ResourceManager.GetString("PassportCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Expiry Date.
        /// </summary>
        public static string PassportExpiryDate {
            get {
                return ResourceManager.GetString("PassportExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Type.
        /// </summary>
        public static string PhoneType {
            get {
                return ResourceManager.GetString("PhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Box Number.
        /// </summary>
        public static string POBoxNumber {
            get {
                return ResourceManager.GetString("POBoxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string StreetAddress {
            get {
                return ResourceManager.GetString("StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Region.
        /// </summary>
        public static string SubRegion {
            get {
                return ResourceManager.GetString("SubRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Expiry Date.
        /// </summary>
        public static string VisaExpiryDate {
            get {
                return ResourceManager.GetString("VisaExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Issuing  Country.
        /// </summary>
        public static string VisaIssuingCountry {
            get {
                return ResourceManager.GetString("VisaIssuingCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Number.
        /// </summary>
        public static string VisaNumber {
            get {
                return ResourceManager.GetString("VisaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Address.
        /// </summary>
        public static string WebAddress {
            get {
                return ResourceManager.GetString("WebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Page.
        /// </summary>
        public static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace.
        /// </summary>
        public static string Workplace {
            get {
                return ResourceManager.GetString("Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
