//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cares.Web.Resources.Vehicle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Vehicle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vehicle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cares.Web.Resources.Vehicle.Vehicle", typeof(Vehicle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Accessories {
            get {
                return ResourceManager.GetString("Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To List.
        /// </summary>
        public static string AddToList {
            get {
                return ResourceManager.GetString("AddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alloy Rim.
        /// </summary>
        public static string AlloyRim {
            get {
                return ResourceManager.GetString("AlloyRim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At location.
        /// </summary>
        public static string AtLocation {
            get {
                return ResourceManager.GetString("AtLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/Wheel Size (Inches).
        /// </summary>
        public static string BackWheelSize {
            get {
                return ResourceManager.GetString("BackWheelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Owner.
        /// </summary>
        public static string BranchOwner {
            get {
                return ResourceManager.GetString("BranchOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Partner.
        /// </summary>
        public static string BusinessPartner {
            get {
                return ResourceManager.GetString("BusinessPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chasis Number.
        /// </summary>
        public static string ChasisNumber {
            get {
                return ResourceManager.GetString("ChasisNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist Item.
        /// </summary>
        public static string CheckListItem {
            get {
                return ResourceManager.GetString("CheckListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage Limit.
        /// </summary>
        public static string CoverageLimit {
            get {
                return ResourceManager.GetString("CoverageLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Vehicle.
        /// </summary>
        public static string CreateNewVehicle {
            get {
                return ResourceManager.GetString("CreateNewVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Odometer.
        /// </summary>
        public static string CurrentOdometer {
            get {
                return ResourceManager.GetString("CurrentOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation Info.
        /// </summary>
        public static string DepreciationInfo {
            get {
                return ResourceManager.GetString("DepreciationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposal Cost.
        /// </summary>
        public static string DisposalCost {
            get {
                return ResourceManager.GetString("DisposalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposa lDate.
        /// </summary>
        public static string DisposalDate {
            get {
                return ResourceManager.GetString("DisposalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposal Description.
        /// </summary>
        public static string DisposalDescription {
            get {
                return ResourceManager.GetString("DisposalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposal Info.
        /// </summary>
        public static string DisposalInfo {
            get {
                return ResourceManager.GetString("DisposalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Payment.
        /// </summary>
        public static string DownPayment {
            get {
                return ResourceManager.GetString("DownPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine CC.
        /// </summary>
        public static string EngineCC {
            get {
                return ResourceManager.GetString("EngineCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Number.
        /// </summary>
        public static string EngineNumber {
            get {
                return ResourceManager.GetString("EngineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Month Dep..
        /// </summary>
        public static string FirstMonthDep {
            get {
                return ResourceManager.GetString("FirstMonthDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Payment.
        /// </summary>
        public static string FirstPayment {
            get {
                return ResourceManager.GetString("FirstPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Payment Date.
        /// </summary>
        public static string FirstPaymentDate {
            get {
                return ResourceManager.GetString("FirstPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Pool.
        /// </summary>
        public static string FleetPool {
            get {
                return ResourceManager.GetString("FleetPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency(Days).
        /// </summary>
        public static string FrequencyInDays {
            get {
                return ResourceManager.GetString("FrequencyInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency(KM).
        /// </summary>
        public static string FrequencyInKM {
            get {
                return ResourceManager.GetString("FrequencyInKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F/Wheel Size (Inches).
        /// </summary>
        public static string FrontWheelSize {
            get {
                return ResourceManager.GetString("FrontWheelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Level (%).
        /// </summary>
        public static string FuelLevel {
            get {
                return ResourceManager.GetString("FuelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HireGroup.
        /// </summary>
        public static string HireGroup {
            get {
                return ResourceManager.GetString("HireGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Odometer.
        /// </summary>
        public static string InitialOdometer {
            get {
                return ResourceManager.GetString("InitialOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Agent.
        /// </summary>
        public static string InsuranceAgent {
            get {
                return ResourceManager.GetString("InsuranceAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Info.
        /// </summary>
        public static string InsuranceInfo {
            get {
                return ResourceManager.GetString("InsuranceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Renewal Date.
        /// </summary>
        public static string InsuranceRenewalDate {
            get {
                return ResourceManager.GetString("InsuranceRenewalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Start Date.
        /// </summary>
        public static string InsuranceStartDate {
            get {
                return ResourceManager.GetString("InsuranceStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Type.
        /// </summary>
        public static string InsuranceType {
            get {
                return ResourceManager.GetString("InsuranceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured Value .
        /// </summary>
        public static string InsuredValue {
            get {
                return ResourceManager.GetString("InsuredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate(%).
        /// </summary>
        public static string InterestRate {
            get {
                return ResourceManager.GetString("InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior Description.
        /// </summary>
        public static string InteriorDescription {
            get {
                return ResourceManager.GetString("InteriorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Code.
        /// </summary>
        public static string KeyCode {
            get {
                return ResourceManager.GetString("KeyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month Dep..
        /// </summary>
        public static string LastMonthDep {
            get {
                return ResourceManager.GetString("LastMonthDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Payment.
        /// </summary>
        public static string LastPayment {
            get {
                return ResourceManager.GetString("LastPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leased Finish Date.
        /// </summary>
        public static string LeasedFinishDate {
            get {
                return ResourceManager.GetString("LeasedFinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leased Ownership?.
        /// </summary>
        public static string LeasedOwnership {
            get {
                return ResourceManager.GetString("LeasedOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leased Start Date.
        /// </summary>
        public static string LeasedStartDate {
            get {
                return ResourceManager.GetString("LeasedStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease Info.
        /// </summary>
        public static string LeaseInfo {
            get {
                return ResourceManager.GetString("LeaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load base data..
        /// </summary>
        public static string LoadBaseDataFailedMsg {
            get {
                return ResourceManager.GetString("LoadBaseDataFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Schedule.
        /// </summary>
        public static string MaintenanceSchedule {
            get {
                return ResourceManager.GetString("MaintenanceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Start Date.
        /// </summary>
        public static string MaintenanceStartDate {
            get {
                return ResourceManager.GetString("MaintenanceStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Type.
        /// </summary>
        public static string MaintenanceType {
            get {
                return ResourceManager.GetString("MaintenanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year.
        /// </summary>
        public static string ModelYear {
            get {
                return ResourceManager.GetString("ModelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Dep..
        /// </summary>
        public static string MonthlyDep {
            get {
                return ResourceManager.GetString("MonthlyDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Payment.
        /// </summary>
        public static string MonthlyPayment {
            get {
                return ResourceManager.GetString("MonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Cylinders.
        /// </summary>
        public static string NumberOfCylinders {
            get {
                return ResourceManager.GetString("NumberOfCylinders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Doors.
        /// </summary>
        public static string NumberofDoors {
            get {
                return ResourceManager.GetString("NumberofDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer.
        /// </summary>
        public static string Odometer {
            get {
                return ResourceManager.GetString("Odometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Details.
        /// </summary>
        public static string OtherDetails {
            get {
                return ResourceManager.GetString("OtherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate #.
        /// </summary>
        public static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Payment.
        /// </summary>
        public static string PrincipalPayment {
            get {
                return ResourceManager.GetString("PrincipalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Cost.
        /// </summary>
        public static string PurchaseCost {
            get {
                return ResourceManager.GetString("PurchaseCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Description.
        /// </summary>
        public static string PurchaseDescription {
            get {
                return ResourceManager.GetString("PurchaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Info.
        /// </summary>
        public static string PurchaseInfo {
            get {
                return ResourceManager.GetString("PurchaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Number.
        /// </summary>
        public static string PurchaseOrderNumber {
            get {
                return ResourceManager.GetString("PurchaseOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Code.
        /// </summary>
        public static string RadioCode {
            get {
                return ResourceManager.GetString("RadioCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Date.
        /// </summary>
        public static string RegisterationDate {
            get {
                return ResourceManager.GetString("RegisterationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Exp. Date.
        /// </summary>
        public static string RegisterationExpDate {
            get {
                return ResourceManager.GetString("RegisterationExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual Value.
        /// </summary>
        public static string ResidualValue {
            get {
                return ResourceManager.GetString("ResidualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Size (ltrs).
        /// </summary>
        public static string TankSize {
            get {
                return ResourceManager.GetString("TankSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Speed (km/h).
        /// </summary>
        public static string TopSpeed {
            get {
                return ResourceManager.GetString("TopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission Type.
        /// </summary>
        public static string TransmissionType {
            get {
                return ResourceManager.GetString("TransmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Vehicle?.
        /// </summary>
        public static string UsedVehicle {
            get {
                return ResourceManager.GetString("UsedVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Period End Date.
        /// </summary>
        public static string UsefulPeriodEndDate {
            get {
                return ResourceManager.GetString("UsefulPeriodEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Period Start Date.
        /// </summary>
        public static string UsefulPeriodStartDate {
            get {
                return ResourceManager.GetString("UsefulPeriodStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string VehicleCategory {
            get {
                return ResourceManager.GetString("VehicleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Checklist.
        /// </summary>
        public static string VehicleCheckList {
            get {
                return ResourceManager.GetString("VehicleCheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete vehicle..
        /// </summary>
        public static string VehicleDeleteErrorMsg {
            get {
                return ResourceManager.GetString("VehicleDeleteErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle successfully deleted..
        /// </summary>
        public static string VehicleDeleteSuccessMsg {
            get {
                return ResourceManager.GetString("VehicleDeleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Details.
        /// </summary>
        public static string VehicleDetail {
            get {
                return ResourceManager.GetString("VehicleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Vehicle details..
        /// </summary>
        public static string VehicleDetailFailedMsg {
            get {
                return ResourceManager.GetString("VehicleDetailFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string VehicleLabel {
            get {
                return ResourceManager.GetString("VehicleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load vehicles..
        /// </summary>
        public static string VehicleLoadFailedMsg {
            get {
                return ResourceManager.GetString("VehicleLoadFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string VehicleMake {
            get {
                return ResourceManager.GetString("VehicleMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string VehicleModel {
            get {
                return ResourceManager.GetString("VehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Name.
        /// </summary>
        public static string VehicleName {
            get {
                return ResourceManager.GetString("VehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Pictorial Condition.
        /// </summary>
        public static string VehiclePictorialCondition {
            get {
                return ResourceManager.GetString("VehiclePictorialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save vehicle..
        /// </summary>
        public static string VehicleSaveErrorMsg {
            get {
                return ResourceManager.GetString("VehicleSaveErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle successfully saved..
        /// </summary>
        public static string VehicleSaveSuccessMsg {
            get {
                return ResourceManager.GetString("VehicleSaveSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
