//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cares.Web.Resources.Organization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkLocation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkLocation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cares.Web.Resources.Organization.WorkLocation", typeof(WorkLocation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phones.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Type.
        /// </summary>
        public static string PhoneType {
            get {
                return ResourceManager.GetString("PhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O.Box.
        /// </summary>
        public static string POBox {
            get {
                return ResourceManager.GetString("POBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serach.
        /// </summary>
        public static string Serach {
            get {
                return ResourceManager.GetString("Serach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string StreetAddress {
            get {
                return ResourceManager.GetString("StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Region.
        /// </summary>
        public static string SubRegion {
            get {
                return ResourceManager.GetString("SubRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Page.
        /// </summary>
        public static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Code.
        /// </summary>
        public static string WorkLocationCode {
            get {
                return ResourceManager.GetString("WorkLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Location failed to delete.
        /// </summary>
        public static string WorkLocationDeleteFailError {
            get {
                return ResourceManager.GetString("WorkLocationDeleteFailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Location successfully deleted.
        /// </summary>
        public static string WorkLocationDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("WorkLocationDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Location Detail.
        /// </summary>
        public static string WorkLocationDetail {
            get {
                return ResourceManager.GetString("WorkLocationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Location.
        /// </summary>
        public static string WorkLocationLabel {
            get {
                return ResourceManager.GetString("WorkLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Location base data failed to load.
        /// </summary>
        public static string WorkLocationLoadBaseFailError {
            get {
                return ResourceManager.GetString("WorkLocationLoadBaseFailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Location failed to load.
        /// </summary>
        public static string WorkLocationLoadFailError {
            get {
                return ResourceManager.GetString("WorkLocationLoadFailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Name.
        /// </summary>
        public static string WorkLocationName {
            get {
                return ResourceManager.GetString("WorkLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Location failed to save.
        /// </summary>
        public static string WorkLocationSaveFailError {
            get {
                return ResourceManager.GetString("WorkLocationSaveFailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Location successfully saved.
        /// </summary>
        public static string WorkLocationSaveSuccessMessage {
            get {
                return ResourceManager.GetString("WorkLocationSaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
