//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cares.Web.Resources.Tariff {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdditionalDriverChrg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdditionalDriverChrg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cares.Web.Resources.Tariff.AdditionalDriverChrg", typeof(AdditionalDriverChrg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add. Driver Rate Revisions.
        /// </summary>
        public static string AddDriverRateRevisions {
            get {
                return ResourceManager.GetString("AddDriverRateRevisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Driver Charge.
        /// </summary>
        public static string AdditionalDriverCharge {
            get {
                return ResourceManager.GetString("AdditionalDriverCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load save Additional Driver Charge..
        /// </summary>
        public static string AdditionalDriverChargeAddFailedMsg {
            get {
                return ResourceManager.GetString("AdditionalDriverChargeAddFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Driver Charge saved successfully..
        /// </summary>
        public static string AdditionalDriverChargeAddSuccessMsg {
            get {
                return ResourceManager.GetString("AdditionalDriverChargeAddSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete Additional Driver Charges.
        /// </summary>
        public static string AdditionalDriverChargeDeleteFailMsg {
            get {
                return ResourceManager.GetString("AdditionalDriverChargeDeleteFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Driver Charge deleted successfully..
        /// </summary>
        public static string AdditionalDriverChargeDeleteSuccessMsg {
            get {
                return ResourceManager.GetString("AdditionalDriverChargeDeleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Driver Charge Detail.
        /// </summary>
        public static string AdditionalDriverChargeDetail {
            get {
                return ResourceManager.GetString("AdditionalDriverChargeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Additional Driver Charges.
        /// </summary>
        public static string AdditionalDriverChargeLoadFailedMsg {
            get {
                return ResourceManager.GetString("AdditionalDriverChargeLoadFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Driver Charges.
        /// </summary>
        public static string AdditionalDriverCharges {
            get {
                return ResourceManager.GetString("AdditionalDriverCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Driver Rate.
        /// </summary>
        public static string AdditionalDriverRate {
            get {
                return ResourceManager.GetString("AdditionalDriverRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Start Date.
        /// </summary>
        public static string EffectiveStartDate {
            get {
                return ResourceManager.GetString("EffectiveStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Additional Driver Charge Detail..
        /// </summary>
        public static string LoadAddDriverChargeDetailFailedMsg {
            get {
                return ResourceManager.GetString("LoadAddDriverChargeDetailFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load base data..
        /// </summary>
        public static string loadBaseDataFailedMsg {
            get {
                return ResourceManager.GetString("loadBaseDataFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Number.
        /// </summary>
        public static string RevisionNumber {
            get {
                return ResourceManager.GetString("RevisionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Type.
        /// </summary>
        public static string TariffType {
            get {
                return ResourceManager.GetString("TariffType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Type Code.
        /// </summary>
        public static string TariffTypeCode {
            get {
                return ResourceManager.GetString("TariffTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Type Name.
        /// </summary>
        public static string TariffTypeName {
            get {
                return ResourceManager.GetString("TariffTypeName", resourceCulture);
            }
        }
    }
}
