//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cares.Web.Resources.Tariff {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceRate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceRate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cares.Web.Resources.Tariff.ServiceRate", typeof(ServiceRate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Service Rate.
        /// </summary>
        public static string CreateNewServiceRate {
            get {
                return ResourceManager.GetString("CreateNewServiceRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective From.
        /// </summary>
        public static string EffectiveFrom {
            get {
                return ResourceManager.GetString("EffectiveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load base data..
        /// </summary>
        public static string LoadBaseDataFailedMsg {
            get {
                return ResourceManager.GetString("LoadBaseDataFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Item.
        /// </summary>
        public static string ServiceItem {
            get {
                return ResourceManager.GetString("ServiceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Item Rate.
        /// </summary>
        public static string ServiceItemRate {
            get {
                return ResourceManager.GetString("ServiceItemRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Service Item Rates..
        /// </summary>
        public static string ServiceItemRatesFailedMsg {
            get {
                return ResourceManager.GetString("ServiceItemRatesFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save Service Rate..
        /// </summary>
        public static string ServiceRateAddFailedMsg {
            get {
                return ResourceManager.GetString("ServiceRateAddFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Rate saved successfully..
        /// </summary>
        public static string ServiceRateAddSuccessMsg {
            get {
                return ResourceManager.GetString("ServiceRateAddSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Rate Code.
        /// </summary>
        public static string ServiceRateCode {
            get {
                return ResourceManager.GetString("ServiceRateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove Service Rate.
        /// </summary>
        public static string ServiceRateDeleteFailedMsg {
            get {
                return ResourceManager.GetString("ServiceRateDeleteFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Rate removed successfully..
        /// </summary>
        public static string ServiceRateDeleteSuccessMsg {
            get {
                return ResourceManager.GetString("ServiceRateDeleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Rate Detail.
        /// </summary>
        public static string ServiceRateDetail {
            get {
                return ResourceManager.GetString("ServiceRateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Rate Name.
        /// </summary>
        public static string ServiceRateName {
            get {
                return ResourceManager.GetString("ServiceRateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Service Rates..
        /// </summary>
        public static string ServiceRatesLoadFailedMsg {
            get {
                return ResourceManager.GetString("ServiceRatesLoadFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Rate.
        /// </summary>
        public static string ServiceRateText {
            get {
                return ResourceManager.GetString("ServiceRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Effective.
        /// </summary>
        public static string StartEffective {
            get {
                return ResourceManager.GetString("StartEffective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Type.
        /// </summary>
        public static string TariffType {
            get {
                return ResourceManager.GetString("TariffType", resourceCulture);
            }
        }
    }
}
