//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cares.Web.Resources.Tariff {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TariffRate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TariffRate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cares.Web.Resources.Tariff.TariffRate", typeof(TariffRate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed.
        /// </summary>
        public static string Allowed {
            get {
                return ResourceManager.GetString("Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Tariff Rate.
        /// </summary>
        public static string CreateNewTarifRate {
            get {
                return ResourceManager.GetString("CreateNewTarifRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current defined Effective Start and End range falls within the duration of another Standard Rate..
        /// </summary>
        public static string CurrentStandardRtOverlaps {
            get {
                return ResourceManager.GetString("CurrentStandardRtOverlaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Effective Date.
        /// </summary>
        public static string EndEffectiveDate {
            get {
                return ResourceManager.GetString("EndEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Effective Date is greater than the start Effective Date of an existing Standard Rate..
        /// </summary>
        public static string EndStandardRtDurationOverlaps {
            get {
                return ResourceManager.GetString("EndStandardRtDurationOverlaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excess.
        /// </summary>
        public static string Excess {
            get {
                return ResourceManager.GetString("Excess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Standard Rate duration falls within the current defined Effective Start and End range..
        /// </summary>
        public static string ExistingStandardRtOverlaps {
            get {
                return ResourceManager.GetString("ExistingStandardRtOverlaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire.
        /// </summary>
        public static string Hire {
            get {
                return ResourceManager.GetString("Hire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Group.
        /// </summary>
        public static string HireGroup {
            get {
                return ResourceManager.GetString("HireGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Hire Group Rates.
        /// </summary>
        public static string HireGroupRateLoadFailedMsg {
            get {
                return ResourceManager.GetString("HireGroupRateLoadFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Effective Date must be greater than the Start Date..
        /// </summary>
        public static string InvalidEndDate {
            get {
                return ResourceManager.GetString("InvalidEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Effective Date must be a current or future date..
        /// </summary>
        public static string InvalidStartDate {
            get {
                return ResourceManager.GetString("InvalidStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load base data..
        /// </summary>
        public static string LoadBaseDataFailedMsg {
            get {
                return ResourceManager.GetString("LoadBaseDataFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load tariff rates..
        /// </summary>
        public static string LoadTariffRatesFailedMsg {
            get {
                return ResourceManager.GetString("LoadTariffRatesFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        public static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage Charge.
        /// </summary>
        public static string MileageCharge {
            get {
                return ResourceManager.GetString("MileageCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string ModelYear {
            get {
                return ResourceManager.GetString("ModelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Effective Date.
        /// </summary>
        public static string StartEffectiveDate {
            get {
                return ResourceManager.GetString("StartEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Rate Code.
        /// </summary>
        public static string TariffRateCode {
            get {
                return ResourceManager.GetString("TariffRateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove tariff rate..
        /// </summary>
        public static string TariffRateDeleteFailedMsg {
            get {
                return ResourceManager.GetString("TariffRateDeleteFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Rate removed successfully..
        /// </summary>
        public static string TariffRateDeleteSuccessMsg {
            get {
                return ResourceManager.GetString("TariffRateDeleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Rate Detail.
        /// </summary>
        public static string TariffRateDetail {
            get {
                return ResourceManager.GetString("TariffRateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Rate Name.
        /// </summary>
        public static string TariffRateName {
            get {
                return ResourceManager.GetString("TariffRateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Rates.
        /// </summary>
        public static string TariffRates {
            get {
                return ResourceManager.GetString("TariffRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save Tariff Rate..
        /// </summary>
        public static string TariffRateSaveFailedMsg {
            get {
                return ResourceManager.GetString("TariffRateSaveFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Rate saved successfully..
        /// </summary>
        public static string TariffRateSaveSuccessMsg {
            get {
                return ResourceManager.GetString("TariffRateSaveSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Rate.
        /// </summary>
        public static string TariffRateText {
            get {
                return ResourceManager.GetString("TariffRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Type.
        /// </summary>
        public static string TariffType {
            get {
                return ResourceManager.GetString("TariffType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Types.
        /// </summary>
        public static string TariffTypes {
            get {
                return ResourceManager.GetString("TariffTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Category.
        /// </summary>
        public static string VehicleCategory {
            get {
                return ResourceManager.GetString("VehicleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Make.
        /// </summary>
        public static string VehicleMake {
            get {
                return ResourceManager.GetString("VehicleMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model.
        /// </summary>
        public static string VehicleModel {
            get {
                return ResourceManager.GetString("VehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
