//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cares.Web.Resources.NonRevenueTicket {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Nrt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Nrt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cares.Web.Resources.NonRevenueTicket.Nrt", typeof(Nrt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Chauffeur.
        /// </summary>
        public static string AddChauffeur {
            get {
                return ResourceManager.GetString("AddChauffeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit.
        /// </summary>
        public static string AddEdit {
            get {
                return ResourceManager.GetString("AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Charge Type Code.
        /// </summary>
        public static string AdditionalChargeTypeCode {
            get {
                return ResourceManager.GetString("AdditionalChargeTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Charge Type Name.
        /// </summary>
        public static string AdditionalChargeTypeName {
            get {
                return ResourceManager.GetString("AdditionalChargeTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vehicle Detail.
        /// </summary>
        public static string AddVehicleDetail {
            get {
                return ResourceManager.GetString("AddVehicleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chauffeur.
        /// </summary>
        public static string Chauffeur {
            get {
                return ResourceManager.GetString("Chauffeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chauffeur Code.
        /// </summary>
        public static string ChauffeurCode {
            get {
                return ResourceManager.GetString("ChauffeurCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chauffeur Name.
        /// </summary>
        public static string ChauffeurName {
            get {
                return ResourceManager.GetString("ChauffeurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Ticket.
        /// </summary>
        public static string CloseTicket {
            get {
                return ResourceManager.GetString("CloseTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition In.
        /// </summary>
        public static string ConditionIn {
            get {
                return ResourceManager.GetString("ConditionIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Out.
        /// </summary>
        public static string ConditionOut {
            get {
                return ResourceManager.GetString("ConditionOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Odemetor.
        /// </summary>
        public static string CurrentOdemetor {
            get {
                return ResourceManager.GetString("CurrentOdemetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date/Time.
        /// </summary>
        public static string EndDateTime {
            get {
                return ResourceManager.GetString("EndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Hour.
        /// </summary>
        public static string EndHour {
            get {
                return ResourceManager.GetString("EndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Minute.
        /// </summary>
        public static string EndMinute {
            get {
                return ResourceManager.GetString("EndMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Difference (ltrs).
        /// </summary>
        public static string FuelDifference {
            get {
                return ResourceManager.GetString("FuelDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel In.
        /// </summary>
        public static string FuelIn {
            get {
                return ResourceManager.GetString("FuelIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Out.
        /// </summary>
        public static string FuelOut {
            get {
                return ResourceManager.GetString("FuelOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Group.
        /// </summary>
        public static string HireGroup {
            get {
                return ResourceManager.GetString("HireGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Date/Time.
        /// </summary>
        public static string InDateTime {
            get {
                return ResourceManager.GetString("InDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Expiry.
        /// </summary>
        public static string LicenseExpiry {
            get {
                return ResourceManager.GetString("LicenseExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Expiry Date.
        /// </summary>
        public static string LicenseExpiryDate {
            get {
                return ResourceManager.GetString("LicenseExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License No..
        /// </summary>
        public static string LicenseNumber {
            get {
                return ResourceManager.GetString("LicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load base data..
        /// </summary>
        public static string LoadBaseDataFailedMsg {
            get {
                return ResourceManager.GetString("LoadBaseDataFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load chauffeurs..
        /// </summary>
        public static string LoadChuaffeurFailedMsg {
            get {
                return ResourceManager.GetString("LoadChuaffeurFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load maintenance activities..
        /// </summary>
        public static string LoadMaintenanceActivityFailedMsg {
            get {
                return ResourceManager.GetString("LoadMaintenanceActivityFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load vehicles..
        /// </summary>
        public static string LoadVehicleFailedMsg {
            get {
                return ResourceManager.GetString("LoadVehicleFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Activities.
        /// </summary>
        public static string MaintenanceActivities {
            get {
                return ResourceManager.GetString("MaintenanceActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year.
        /// </summary>
        public static string ModelYear {
            get {
                return ResourceManager.GetString("ModelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Revenue Ticket.
        /// </summary>
        public static string NRT {
            get {
                return ResourceManager.GetString("NRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Revenue Ticket has been successfully closed..
        /// </summary>
        public static string NRTCloseSuccessMsg {
            get {
                return ResourceManager.GetString("NRTCloseSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Non Revenue Ticket..
        /// </summary>
        public static string NRTDetailFailedMsg {
            get {
                return ResourceManager.GetString("NRTDetailFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Revenue Ticket #.
        /// </summary>
        public static string NRTNumber {
            get {
                return ResourceManager.GetString("NRTNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Open Ticket..
        /// </summary>
        public static string NRTOpenFailedMsg {
            get {
                return ResourceManager.GetString("NRTOpenFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Revenue Ticket has been successfully opened..
        /// </summary>
        public static string NRTOpenSuccessMsg {
            get {
                return ResourceManager.GetString("NRTOpenSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRT Type.
        /// </summary>
        public static string NRTTYpe {
            get {
                return ResourceManager.GetString("NRTTYpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer In.
        /// </summary>
        public static string OdometerIn {
            get {
                return ResourceManager.GetString("OdometerIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Out.
        /// </summary>
        public static string OdometerOut {
            get {
                return ResourceManager.GetString("OdometerOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Ticket.
        /// </summary>
        public static string OpenTicket {
            get {
                return ResourceManager.GetString("OpenTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Date/Time.
        /// </summary>
        public static string OutDateTime {
            get {
                return ResourceManager.GetString("OutDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Location.
        /// </summary>
        public static string OutLocation {
            get {
                return ResourceManager.GetString("OutLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Number.
        /// </summary>
        public static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Location.
        /// </summary>
        public static string ReturnLocation {
            get {
                return ResourceManager.GetString("ReturnLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Vehicle?.
        /// </summary>
        public static string ReturnVehicle {
            get {
                return ResourceManager.GetString("ReturnVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date/Time.
        /// </summary>
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Hour.
        /// </summary>
        public static string StartHour {
            get {
                return ResourceManager.GetString("StartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minute.
        /// </summary>
        public static string StartMinute {
            get {
                return ResourceManager.GetString("StartMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Size.
        /// </summary>
        public static string TankSize {
            get {
                return ResourceManager.GetString("TankSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rate.
        /// </summary>
        public static string TotalRate {
            get {
                return ResourceManager.GetString("TotalRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Ticket.
        /// </summary>
        public static string UpdateTicket {
            get {
                return ResourceManager.GetString("UpdateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Category.
        /// </summary>
        public static string VehicleCategory {
            get {
                return ResourceManager.GetString("VehicleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Details.
        /// </summary>
        public static string VehicleDetails {
            get {
                return ResourceManager.GetString("VehicleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle In Status.
        /// </summary>
        public static string VehicleInStatus {
            get {
                return ResourceManager.GetString("VehicleInStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Make.
        /// </summary>
        public static string VehicleMake {
            get {
                return ResourceManager.GetString("VehicleMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model.
        /// </summary>
        public static string VehicleModel {
            get {
                return ResourceManager.GetString("VehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Out Status.
        /// </summary>
        public static string VehicleOutStatus {
            get {
                return ResourceManager.GetString("VehicleOutStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Plate Number.
        /// </summary>
        public static string VehiclePlateNumber {
            get {
                return ResourceManager.GetString("VehiclePlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Status.
        /// </summary>
        public static string VehicleStatus {
            get {
                return ResourceManager.GetString("VehicleStatus", resourceCulture);
            }
        }
    }
}
